---

coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true


flag_management: {}

ignore:
  - "src/reference/utils.tsx"
  - "src/registry/file/test-utils.ts"
  - "src/tests/map.tsx"
