name: Run CI build and tests

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches:
      - main
      - stable/*
    tags:
      - '*'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  workflow_dispatch:

permissions: {}

concurrency:
  group: '${{ github.workflow }}-${{ github.ref_name }}' # unique builds for branch/tag name
  cancel-in-progress: false  # do not cancel in progress, but only in-between builds

jobs:
  setup:
    name: Set up the build variables
    runs-on: ubuntu-latest
    outputs:
      # see https://github.com/orgs/community/discussions/26671
      version: ${{ steps.vars.outputs.version }}
      git_hash: ${{ steps.vars.outputs.git_hash }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false
      - name: Extract version info
        id: vars
        uses: maykinmedia/open-api-workflows/actions/extract-version@79102b911003d75203ca2fed7df01ad79d9b6bba # v6

  storybook:
    name: Create storybook build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version-file: '.nvmrc'
          package-manager-cache: 'false'

      - name: Build Storybook docs
        run: |
          npm ci
          npm run compilemessages
          npm run build-storybook -- --stats-json --quiet

      - name: Upload artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3
        with:
          path: ./storybook-static

  build-package:
    name: Create 'production' build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version-file: '.nvmrc'
          package-manager-cache: 'false'

      - name: Install dependencies
        run: npm ci

      - name: Build library
        run: |
          npm run compilemessages
          npm run build:typecheck
          npm run build

          if [ -d "./dist/node_modules" ]; then
            echo "Unexpected 'node_modules' in dist directory!"
            exit 1
          fi

      - name: Store build artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: build
          path: dist/
          retention-days: 1

  prettier:
    name: prettier (code formatting)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version-file: '.nvmrc'
          package-manager-cache: 'false'

      - name: Install dependencies
        run: npm ci

      - name: Run prettier linter
        run: npm run checkformat

  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version-file: '.nvmrc'
          package-manager-cache: 'false'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: |
          npm run test:vitest -- --coverage

      - name: Publish coverage report
        uses: codecov/codecov-action@0fb7174895f61a3b6b78fc075e0cd60383518dac # v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: vitest

  interaction-tests:
    name: Run Storybook tests
    runs-on: ubuntu-22.04
    needs:
      - storybook

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version-file: '.nvmrc'
          package-manager-cache: 'false'

      - name: Install dependencies
        run: npm ci

      # Reference: https://storybook.js.org/docs/6.5/react/writing-tests/test-runner#run-against-non-deployed-storybooks
      - name: Set up test environment
        run: |
          npx playwright install --with-deps
          npm run compilemessages

      - name: Download storybook artifact
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          name: github-pages
          path: storybook-static

      - name: Serve storybook and run tests
        run: |
          cd storybook-static/ && tar -xvf artifact.tar && cd ..
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "npx http-server storybook-static --port 6006 --quiet" \
            "npx wait-on -l http://127.0.0.1:6006 && npm run test:storybook"
          # Prepare coverage
          npx nyc report --reporter=lcov -t coverage/storybook --report-dir coverage/storybook

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@0fb7174895f61a3b6b78fc075e0cd60383518dac # v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: storybook

  i18n-check:
    name: Check i18n messages extracted
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false
      - uses: open-formulieren/actions/check-message-extraction@599d67bf43a0c630d26675244a2d4774835a6897 # v1
        with:
          paths: i18n/{compiled,messages}
          extraction-command: ./bin/makemessages.sh
          compilation-command: npm run compilemessages

      # Only actually does anything in release/* branches or for pushed tags
      - uses: open-formulieren/actions/check-missing-translations@599d67bf43a0c630d26675244a2d4774835a6897 # v1
        with:
          messages-path: i18n/messages
          locales: nl

  deploy:
    runs-on: ubuntu-latest
    needs:
      - storybook
      - unit-tests
      - interaction-tests
      - prettier
      - i18n-check
    # do not run in forks & only publish main branch
    if: github.ref_name == 'main' && github.repository_owner == 'open-formulieren'

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@1f0c5cde4bc74cd7e1254d0cb4de8d49e9068c7d # v4
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4

  chromatic:
    name: Visual regression test with Chromatic
    runs-on: ubuntu-latest
    needs:
      - storybook

    # do not run in forks
    if: github.event_name == 'push' || ! github.event.pull_request.head.repo.fork

    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0 # 👈 Required to retrieve git history
          persist-credentials: false

      - name: Download build artifact
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          name: github-pages
          path: ./storybook-static

      - name: Extract artifact
        run: |
          tar -xvf artifact.tar
          rm artifact.tar
        working-directory: ./storybook-static

      - name: Publish to Chromatic for visual regression tests
        uses: chromaui/action@b5b575184e923495cfbd28d3c0df91b42379c94e  #v18.0.0
        if: github.event.pull_request.draft == false || github.event.push
        with:
          autoAcceptChanges: main
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          storybookBuildDir: ./storybook-static
          onlyChanged: true
          externals: 'src/img/**'

  publish:
    name: Publish the NPM package
    runs-on: ubuntu-latest
    needs:
      - setup
      - build-package
      - unit-tests
      - interaction-tests
      - prettier
      - i18n-check

    # do not publish in forks or non-tag pushes
    if: startsWith(github.ref, 'refs/tags/') && github.repository_owner == 'open-formulieren'

    environment:
      name: release
      url: https://www.npmjs.com/package/@open-formulieren/formio-renderer
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version-file: '.nvmrc'
          package-manager-cache: 'false'
          registry-url: 'https://registry.npmjs.org'
          scope: '@open-formulieren'

      - name: Install dependencies
        run: |
          # update npm
          npm install -g npm@latest
          npm install

      - name: Download build artifact
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          name: build
          path: dist/

      - name: Publish package to NPM
        run: |
          case "${NEEDS_SETUP_OUTPUTS_VERSION}" in
            *"-alpha."*) npm_tag=next ;;
            *"-beta."*) npm_tag=next ;;
            *"-rc."*) npm_tag=next ;;
            "1.1."*) npm_tag=stable-1.1.x ;;
            *) npm_tag=latest ;;
          esac

          npm publish --access public --tag="$npm_tag"
        env:
          NEEDS_SETUP_OUTPUTS_VERSION: ${{ needs.setup.outputs.version }}
